name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Set the node version as per your project requirement

    - name: Install Dependencies
      run: npm install

    - name: Build TypeScript App
      run: npm run build  # Ensure this script compiles your TypeScript and outputs to the 'dist' folder

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
